Repository egefellas/shortener, pull requests merged in 2021-08, with the labels that each got.

#1 SH-2 | Adding CODEOWNERS
  CODEOWNERS
Labels: task

#4 SH-3 | Configuring styleci
  .styleci.yml
Labels: task

#5 EF-4 | Adding github actions
  .github/prchecker.json
Labels: story

#6 EF-4 | Adding github actions
  .github/prchecker.json
  .github/workflows/label.yml
Labels: story

#8 EF-17 | Update changelog.md & readme.md
  CHANGELOG.md
  README.md
Labels: documentation

#7 EF-5 | URL shortener API
  app/Http/Controllers/UrlController.php
  app/Models/Url.php
  app/Providers/RepositoryServiceProvider.php
  app/Repositories/UrlRepository.php
  app/Repositories/UrlRepositoryInterface.php
  app/Services/UrlService.php
  config/app.php
  database/factories/UrlFactory.php
  database/migrations/2021_08_04_221529_create_urls_table.php
  routes/api.php
  routes/web.php
  tests/Feature/ExampleTest.php
  tests/Feature/Http/Controller/UrlControllerTest.php
  tests/Feature/TestCase.php
  tests/Suites/RepositoryTestSuite.php
  tests/Suites/ServiceTestSuite.php
  tests/TestCase.php
  tests/Unit/ExampleTest.php
  tests/Unit/Repositories/UrlRepositoryTest.php
  tests/Unit/Services/UrlServiceTest.php
Labels: story

#11 EF-9 | welcome page and layouts create and session key assignment
  app/Providers/AppServiceProvider.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/footer.blade.php
  resources/views/layouts/header.blade.php
  resources/views/welcome.blade.php
  routes/web.php
Labels: story

#12 EF-18 | create form and generating short url
  app/Http/Controllers/UrlController.php
  app/Http/Kernel.php
  app/Http/Middleware/SetCookies.php
  app/Http/Requests/UrlRequest.php
  app/Models/Url.php
  app/Providers/AppServiceProvider.php
  app/Repositories/UrlRepository.php
  app/Repositories/UrlRepositoryInterface.php
  app/Services/UrlService.php
  phpunit.xml
  resources/views/layouts/errors.blade.php
  resources/views/welcome.blade.php
  routes/web.php
  tests/Feature/Http/Controller/UrlControllerTest.php
  tests/Unit/Repositories/UrlRepositoryTest.php
  tests/Unit/Services/UrlServiceTest.php
Labels: story

#14 EF-16 | Add travis-ci for github actions
  .travis.yml
Labels: story

#15 EF-10 | Create redirect page
  .eslintrc.js
  app/Http/Controllers/UrlController.php
  config/session.php
  public/css/app.css
  public/images/hero-pattern.svg
  public/images/workflow-mark-indigo-600.svg
  public/js/app.js
  resources/js/app.js
  resources/js/components/app/Header.vue
  resources/js/components/pages/home/MainFrame.vue
  resources/js/components/pages/redirect/Index.vue
  resources/js/components/pages/redirect/RedirectFrame.vue
  resources/views/layouts/app.blade.php
  resources/views/pages/redirect.blade.php
  tailwind.config.js
  tests/Feature/Http/Controller/UrlControllerTest.php
Labels: story

#18 EF-XXX | remove prod css and js
  .gitignore
  public/css/app.css
  public/js/app.js
  public/js/app.js.LICENSE.txt
Labels: task
